---
title: "Police Complaints"
author: "Stefan Arroyo-Cottier"
date: "10/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(ggplot2)
library(graphics)
library(ftplottools)

# It is somewhat sloppy to include a read_csv() command in the setup chunk.
# Normally, we would just load libraries here. However, we have not learned
# about the col_types argument to read_csv() yet, so we can't make the annoying
# message go away unless we stick the call in a code chunk with a code chunk
# option like message = FALSE or include = FALSE.

raw_data_philly <- read_csv("https://raw.githubusercontent.com/Financial-Times/police-misconduct-complaints-analysis/main/output/philly_clean.csv") %>% 
  select(officer_id) 

raw_data_nyc <- read_csv("https://raw.githubusercontent.com/Financial-Times/police-misconduct-complaints-analysis/main/output/nyc_clean.csv") %>% 
  select(OfficerID) 

raw_data_chicago <- read_csv("https://raw.githubusercontent.com/Financial-Times/police-misconduct-complaints-analysis/main/output/chicago_clean.csv") %>% 
  select(UID) 

```


```{r, clean_data}

# This code makes a table that lets us know how many times each officer id appeared 
# in the tibble, i.e. how many complaints each officer has.

clean_data_philly <- raw_data_philly %>% 
  group_by(officer_id) %>% 
  summarise(total = n()) %>% 
  mutate(compl_dec = ntile(total, 10)) %>% 
  group_by(compl_dec) %>% 
  summarize(compl_total = sum(total)) %>% 
  mutate(compl_perc = compl_total / sum(compl_total)) %>% 
  select(compl_dec, compl_perc) %>% 
  mutate(city = "Philadelphia")

clean_data_nyc <- raw_data_nyc %>% 
  group_by(OfficerID) %>% 
  summarise(total = n()) %>% 
  mutate(compl_dec = ntile(total, 10)) %>% 
  group_by(compl_dec) %>% 
  summarize(compl_total = sum(total)) %>% 
  mutate(compl_perc = compl_total / sum(compl_total)) %>% 
  select(compl_dec, compl_perc) %>% 
  mutate(city = "New York City")

clean_data_chicago <- raw_data_chicago %>% 
  group_by(UID) %>% 
  summarise(total = n()) %>% 
  mutate(compl_dec = ntile(total, 10)) %>% 
  group_by(compl_dec) %>% 
  summarize(compl_total = sum(total)) %>% 
  mutate(compl_perc = compl_total / sum(compl_total)) %>% 
  select(compl_dec, compl_perc) %>% 
  mutate(city = "Chicago")

  fresh <- bind_rows(clean_data_chicago, clean_data_philly, clean_data_nyc)
```

```{r, plot_data}
# We could just have one giant pipe which goes directly into ggplot(), like we
# do in the tutorials. There is nothing wrong with that approach, but it is
# often easier to split your work up into separate parts, the better to make
# sure that each part is doing what you want.

   
fresh %>% 
  ggplot(aes(x = compl_dec, y = compl_perc)) +
    geom_col(fill = if_else(fresh$compl_dec == 10,"#9cc6e6","#1e4570")) +
    facet_wrap(~city)+
    labs(title = "In several US cities, a small group of officers generate a disproportionate \nshare of misconduct complaints",
         subtitle = "Distribution of civilan misconduct complaints, by decile",
         x = "Officers are ranked by number of complaints and grouped into deciles",
         y = NULL,
         caption = "Magic") +
    scale_x_continuous(breaks = 1:10) +
    scale_y_continuous(labels = scales::percent_format(accuracy = 1))+
    ft_theme() +
    annotate("text", x = 5, y = .25, label = "In New York, the top 10%\nof officers who drew\ncomplaints between\n2007 and 2017 were\nresponsible for about\n32% of all complaints\nover the decade")
    
```

